"""Scope-first retrieval domain core."""

from .contracts import (
    DEFAULT_QUERY_POLICY_VERSION,
    RRF_VERSION,
    SEMANTIC_RETRIEVAL_SCHEMA_VERSION,
    CandidateFilterReason,
    CandidateVisibility,
    CorpusQuota,
    FilterCount,
    RawChannelScore,
    RetrievalCandidate,
    RetrievalChannel,
    RetrievalChannelEvidence,
    RetrievalChannelStatus,
    RetrievalDegradationReason,
    RetrievalDiagnostics,
    RetrievalEmptyReason,
    RetrievalEvidenceChunk,
    RetrievalMode,
    RetrievalPerspective,
    RetrievalPolicyV1,
    RetrievalPurpose,
    SearchScope,
    SemanticRetrievalHitV2,
    SemanticSearchRequestV2,
    SemanticSearchResultV2,
    TimelineSearchLimit,
)
from .engine import candidate_filter_reason, filter_candidates, retrieve
from .knowledge import KnowledgeProjectionScope, derive_known_visibility_keys

__all__ = [
    "DEFAULT_QUERY_POLICY_VERSION",
    "RRF_VERSION",
    "SEMANTIC_RETRIEVAL_SCHEMA_VERSION",
    "CandidateFilterReason",
    "CandidateVisibility",
    "CorpusQuota",
    "FilterCount",
    "RawChannelScore",
    "RetrievalCandidate",
    "RetrievalChannel",
    "RetrievalChannelEvidence",
    "RetrievalChannelStatus",
    "RetrievalDegradationReason",
    "RetrievalDiagnostics",
    "RetrievalEmptyReason",
    "RetrievalEvidenceChunk",
    "RetrievalMode",
    "RetrievalPerspective",
    "RetrievalPolicyV1",
    "RetrievalPurpose",
    "SearchScope",
    "SemanticRetrievalHitV2",
    "SemanticSearchRequestV2",
    "SemanticSearchResultV2",
    "TimelineSearchLimit",
    "candidate_filter_reason",
    "filter_candidates",
    "retrieve",
    "KnowledgeProjectionScope",
    "derive_known_visibility_keys",
]
