"""Semantic-index API contracts.

This package intentionally contains no provider client, secret storage, ORM model,
or route registration.  Those concerns are implemented only after the public
contract and its security gates are approved.
"""

from .contracts import (
    EMBEDDING_CONTRACT_VERSION,
    SEMANTIC_SEARCH_SCHEMA_VERSION,
    TARGET_CANDIDATE_DIMENSION,
    TARGET_CANDIDATE_MODEL_ID,
    ConsentAction,
    CredentialAction,
    EmbeddingCandidateTarget,
    EmbeddingConfigResource,
    EmbeddingConnectionStatus,
    EmbeddingCorpus,
    EmbeddingCredentialMutation,
    EmbeddingErrorCode,
    EmbeddingErrorResource,
    EmbeddingGenerationStatus,
    EmbeddingProfileResource,
    NovelEmbeddingConsentMutation,
    NovelEmbeddingConsentResource,
    PerspectiveKind,
    SemanticIndexStatus,
    SemanticMatchChannel,
    SemanticPerspective,
    SemanticSearchHit,
    SemanticSearchMode,
    SemanticSearchRequest,
    SemanticSearchResult,
    SemanticSourceState,
    VerificationStatus,
)

__all__ = [
    "EMBEDDING_CONTRACT_VERSION",
    "SEMANTIC_SEARCH_SCHEMA_VERSION",
    "TARGET_CANDIDATE_DIMENSION",
    "TARGET_CANDIDATE_MODEL_ID",
    "ConsentAction",
    "CredentialAction",
    "EmbeddingCandidateTarget",
    "EmbeddingConfigResource",
    "EmbeddingConnectionStatus",
    "EmbeddingCorpus",
    "EmbeddingCredentialMutation",
    "EmbeddingErrorCode",
    "EmbeddingErrorResource",
    "EmbeddingGenerationStatus",
    "EmbeddingProfileResource",
    "NovelEmbeddingConsentMutation",
    "NovelEmbeddingConsentResource",
    "PerspectiveKind",
    "SemanticIndexStatus",
    "SemanticMatchChannel",
    "SemanticPerspective",
    "SemanticSearchHit",
    "SemanticSearchMode",
    "SemanticSearchRequest",
    "SemanticSearchResult",
    "SemanticSourceState",
    "VerificationStatus",
]
